### ISSUE TITLE
Compiled Jar?

### ISSUE THREAD

**Issue by ghost** [phillmac/IRC-to-TS3-chat#1]
anyway i could get a compiled jar for testing?

**Comment by phillmac** [comment]
[16_10_09_22-24-07.zip](https://github.com/phillmac/ChatBridge/files/518606/16_10_09_22-24-07.zip)
1). extract the contents of that somewhere
2). Edit the yml config files to set up the IRC & TeamSpeak3 server details
3). run this command:
 java -jar console.jar
New releases will be posted at http://oasiscraft.org/phillmac/ChatBridge

**Comment by ghost** [comment]
It connects to both IRC and TS3 but it gives "Can't send to TS3: bot not initalsed yet." when i type a message in IRC server

```
D:\Servers\16_10_09_22-24-07>java -jar console.jar
[main] INFO ro.fortsoft.pf4j.DefaultPluginManager - PF4J version 0.0.0 in 'deplo
yment' mode
[main] INFO ro.fortsoft.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
[main] INFO ro.fortsoft.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
[main] INFO ro.fortsoft.pf4j.DefaultPluginManager - Plugin 'chatbridge' resolved

[main] INFO ro.fortsoft.pf4j.DefaultPluginManager - Start plugin 'chatbridge:1.0
.4'
Chatbridge version 1.0.4.5 initalizing
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/D:/Servers/16_10_09_22-24-07/console.jar!/org
/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/D:/Servers/16_10_09_22-24-07/plugins/ChatBrid
ge-1.0.4/lib/slf4j-simple-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.

SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]
TS3  query port: 10011
IRC onGenericMessage fired
IRC onGenericMessage fired
Oct 09, 2016 7:11:28 PM net.phillm.chatbridge.ChatBridge connectTS3
SEVERE: null
java.lang.NullPointerException
        at net.phillm.chatbridge.TS3Bot.<init>(TS3Bot.java:74)
        at net.phillm.chatbridge.ChatBridge.connectTS3(ChatBridge.java:102)
        at net.phillm.chatbridge.ChatBridge.start(ChatBridge.java:43)
        at ro.fortsoft.pf4j.DefaultPluginManager.startPlugins(DefaultPluginManag
er.java:231)
        at net.phillm.jc2.JC2.run(JC2.java:49)
        at net.phillm.jc2.JC2.main(JC2.java:41)

Info: Type /info to get the build version!
Info: Type /help to get a list of availble commands!
IRC onGenericMessage fired
Can't send to TS3: bot not initalsed yet.
IRC onGenericMessage fired
Can't send to TS3: bot not initalsed yet.
IRC onGenericMessage fired
Can't send to TS3: bot not initalsed yet.
```

**Comment by ghost** [comment]
```
host: "irc.bobisunreal.com"
port: "6667"
channel: "#bobisunreal"
nick: "TS3Bot"
autoreconnect: ""
messageseperator: "Hello"
messageseperatorcolor: ""
messagecolor: ""
```

```
host: "bobisunreal.com"
queryport: "10011"
voiceport: "9987"
username: "serveradmin"
password: "blank"
nick: "IRCbot"
channel: "0"
```

**Comment by phillmac** [comment]
Looking at my code it seems like its looking for a channel name, not an id.
I'll see if I can quickly add channel by id support.
